import { isPlatformBrowser } from '@angular/common';
import {
  afterNextRender,
  Component,
  computed,
  inject,
  PLATFORM_ID,
  signal,
} from '@angular/core';
import { DomSanitizer, type SafeHtml } from '@angular/platform-browser';
import { Toolbar, ToolbarWidget } from '@angular/aria/toolbar';
import { A11yModule, LiveAnnouncer } from '@angular/cdk/a11y';
import {
  loadOrSeed,
  renderPreview,
  resetToSeed,
  saveNewsletter,
  seedNewsletter,
  type Newsletter,
} from '../core';

@Component({
  imports: [Toolbar, ToolbarWidget, A11yModule],
  selector: 'app-root',
  styleUrl: './app.scss',
  templateUrl: './app.html',
})
export class App {
  private readonly platformId = inject(PLATFORM_ID);
  private readonly liveAnnouncer = inject(LiveAnnouncer);
  private readonly sanitizer = inject(DomSanitizer);

  /** Product title — BDD smoke asserts this. */
  protected readonly title = signal('Newsletter Template Editor');

  protected readonly newsletter = signal<Newsletter>(seedNewsletter());

  /** Trusted email HTML for iframe srcdoc (generated by our renderer only). */
  protected readonly previewSrcdoc = computed((): SafeHtml =>
    this.sanitizer.bypassSecurityTrustHtml(renderPreview(this.newsletter())),
  );

  constructor() {
    afterNextRender(() => {
      if (!isPlatformBrowser(this.platformId)) return;
      const loaded = loadOrSeed(seedNewsletter);
      this.newsletter.set(loaded);
      saveNewsletter(loaded);
    });
  }

  protected resetSeed(): void {
    const next = resetToSeed(seedNewsletter);
    this.newsletter.set(next);
    void this.liveAnnouncer.announce('Demo seed restored', 'polite');
  }

  protected save(): void {
    saveNewsletter(this.newsletter());
    void this.liveAnnouncer.announce('Newsletter saved locally', 'polite');
  }
}
